require('dotenv').config();
const http = require('http');
const { Server } = require('socket.io');
const app = require('./src/app');
const connectDB = require('./src/db');
const { startSimulator } = require('./src/simulator/cronJob');
const PORT = process.env.PORT || 5000;
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: process.env.FRONTEND_URL, methods: ['GET','POST'] } });
io.on('connection', (socket) => { console.log('Client connected:', socket.id); socket.on('disconnect', () => console.log('Client disconnected:', socket.id)); });
app.set('io', io);
connectDB().then(() => { server.listen(PORT, () => console.log(`Server running on port ${PORT} — ${process.env.NODE_ENV}`)); startSimulator(io); });
